version: "3"
services:
  app:
    container_name: go-app
    build:
      context: ./server
      dockerfile: ./Dockerfile
    environment:
      - PORT
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/app
